### PR TITLE
Binary search

### PR DESCRIPTION
**Pull request by prasanna16-12**
## What is the change?
created binary search.md
this file contains 
- overview
- explanation
- pseudo code
- code
- time and space complexity
## Related issue?
closes: #26 

## Checklist:
Before you create this PR, confirm all the requirements listed below by checking the checkboxes `[x]`:

-   [x] I have followed the [Code of Conduct](https://github.com/HackClubRAIT/Wizard-Of-Docs/blob/ec224497bce316f7b4736a901f70688f251cca87/CODE_OF_CONDUCT.md).
-   [x] I have checked there aren't other open [Pull Requests](https://github.com/siddhi-244/Embellish/pulls) for the same update/change.
-   [x] I have you tested the code before submission.
-   [x] I have commented on my code, particularly in hard-to-understand areas.
-   [x] My changes generates no new warnings.
-   [x] I'm a Hacktoberfest'21 contributor.

### CODE REVIEW

**Comment by siddhi-244** [comment]
Create a issue first.

**Comment by prasanna16-12** [comment]
i really don't know how to create issue I'm newbie here

**Comment by siddhi-244** [comment]
> i really don't know how to create issue I'm newbie here

Just go to issues section and over there you can create new issues.

**Comment by prasanna16-12** [comment]
what to do next

**Comment by siddhi-244** [comment]
> what to 
Made issue ?

**Comment by prasanna16-12** [comment]
yes

**Comment by siddhi-244** [comment]
> yes

Assigned. Make sure you link this pr to the issue

**Comment by prasanna16-12** [comment]
i changed closes = #26 is it ok now?

**Comment by siddhi-244** [comment]
Ok we will review it.

**Review by siddhi-244 — APPROVED** [review]
Great work🎊🎊

**Comment by prasanna16-12** [comment]
thanks..

**Review by girija0707 — APPROVED** [review]

**Comment by girija0707** [comment]
> thanks..
 great going🦋

**Comment by prasanna16-12** [comment]
so every time I want to make PR.. I have to make an issue first right ?

**Comment by girija0707** [comment]
> so every time I want to make PR.. I have to make an issue first right ?

Yess, then you'll get assigned and then you can start working that's the right procedure

**Pull request merged**
