### PR TITLE
Binary_Search_Java

### PR DESCRIPTION
**Pull request by akankshaa02**
## What is the change?
Added Binary Search Algorithm in java, explained with an example.

## Related issue?
closes: #38 

## Checklist:
Before you create this PR, confirm all the requirements listed below by checking the checkboxes `[x]`:

-   [x] I have followed the [Code of Conduct](https://github.com/HackClubRAIT/Wizard-Of-Docs/blob/ec224497bce316f7b4736a901f70688f251cca87/CODE_OF_CONDUCT.md).
-   [x] I have  checked there aren't other open [Pull Requests](https://github.com/siddhi-244/Embellish/pulls) for the same update/change.
-   [x] I have you tested the code before submission.
-   [x] I have commented my code, particularly in hard-to-understand areas.
-   [x] My changes generates no new warnings.
-   [x] I'm Hacktoberfest'21 contributor.

### CODE REVIEW

**Comment by akankshaa02** [comment]
Added the Binary Search Algorithm in Java with the help of an example. Wrote the code in simpler manner and added proper comments for better understanding.

**Comment by siddhi-244** [comment]
You have to add this in the already created file.

**Comment by akankshaa02** [comment]
okay sure I am adding this to Binary_Search.md

**Comment by akankshaa02** [comment]
Removed the previous Binary_Search_Java and made changes in existing Binary_Search.

**Comment by siddhi-244** [comment]
You can't delete it just try to make changes in existing one

**Comment by akankshaa02** [comment]
Hello Siddhi sorry for the inconvenience but just merge the pull request from here Binary_Search java solution #69. I have made the changes as per your requirement, you may check the branch(akankshaa02-patch-2). Feel free to merge it into the code base.

**Pull request closed without merging**
