### PR TITLE
Create Linear_Search.md

### PR DESCRIPTION
**Pull request by Asmit2952**
## What is the change?
Added info about linear search and a program in c++

## Related issue?
closes: #2 

## Checklist:
Before you create this PR, confirm all the requirements listed below by checking the checkboxes `[x]`:

-   [x] I have followed the [Code of Conduct](https://github.com/HackClubRAIT/Wizard-Of-Docs/blob/ec224497bce316f7b4736a901f70688f251cca87/CODE_OF_CONDUCT.md).
-   [x] I have  checked there aren't other open [Pull Requests](https://github.com/siddhi-244/Embellish/pulls) for the same update/change.
-   [x] I have you tested the code before submission.
-   [x] I have commented my code, particularly in hard-to-understand areas.
-   [x] My changes generates no new warnings.
-   [x] I'm Hacktoberfest'21 contributor.

### CODE REVIEW

**Comment by siddhi-244** [comment]
This is plagiarized.  Please write your own document

**Comment by Asmit2952** [comment]
> This is plagiarized. Please write your own document

Okk I'll make changes

**Review by girija0707 — APPROVED** [review]
LGTM

**Review by siddhi-244 — APPROVED** [review]
LGTM

**Pull request merged**
