### PR TITLE
created quick sort.md with detail explanation

### PR DESCRIPTION
**Pull request by prasanna16-12**
## What is the change?
added quick sort algorithm
 this file contain 
- overview
- explanation
- psudo code
- code
- time and space complexity

## Related issue?
closes: #18

## Checklist:
Before you create this PR, confirm all the requirements listed below by checking the checkboxes `[x]`:

-   [x] I have followed the [Code of Conduct](https://github.com/HackClubRAIT/Wizard-Of-Docs/blob/ec224497bce316f7b4736a901f70688f251cca87/CODE_OF_CONDUCT.md).
-   [x] I have  checked there aren't other open [Pull Requests](https://github.com/siddhi-244/Embellish/pulls) for the same update/change.
-   [x] I have you tested the code before submission.
-   [x] I have commented my code, particularly in hard-to-understand areas.
-   [x] My changes generates no new warnings.
-   [x] I'm Hacktoberfest'21 contributor.

### CODE REVIEW

**Review by siddhi-244 — APPROVED** [review]
Great work🎊🎊🎊🎊

**Comment by prasanna16-12** [comment]
shall I add some more algorithms?

**Comment by siddhi-244** [comment]
> shall I add some more algorithms?

Create new issues

**Comment by prasanna16-12** [comment]
done :)

**Review by girija0707 — APPROVED** [review]
Go ahead and merge it

**Pull request merged**
