### PR TITLE
Fix issue #136 Implementation of queue using linked list and array 

### PR DESCRIPTION
**Pull request by vedsom**
## What is the change?
Implementation of queue using linked list and array

## Related issue?
closes: #136

## Checklist:
Before you create this PR, confirm all the requirements listed below by checking the checkboxes `[x]`:

-   [x] I have followed the [Code of Conduct](https://github.com/HackClubRAIT/Wizard-Of-Docs/blob/ec224497bce316f7b4736a901f70688f251cca87/CODE_OF_CONDUCT.md).
-   [x] I have  checked there aren't other open [Pull Requests](https://github.com/siddhi-244/Embellish/pulls) for the same update/change.
-   [x] I have you tested the code before submission.
-   [x] I have commented my code, particularly in hard-to-understand areas.
-   [x] My changes generates no new warnings.
-   [x] I'm (HSOC) Hack-Club-Rait Summer of code '22 Contributor

### CODE REVIEW

**Comment by vedsom** [comment]
@Chaitalishetty Kindly review the PR!! Thanks

**Comment by Chaitalishetty** [comment]
@vedsom This is a documentation repo pls add some explanation. You can refer to the merged prs.

**Comment by vedsom** [comment]
@Chaitalishetty I have updated both the files as per your choice. Kindly review the PR. Thanks!!

**Comment by Chaitalishetty** [comment]
@vedsom As this is a documentation repo, you need to create .md file. Pls refer to merged prs.

**Review by Chaitalishetty — APPROVED** [review]
LGTM!

**Pull request merged**
