### PR TITLE
Product of Array Except Self.cpp

### PR DESCRIPTION
**Pull request by rohith1125**
## What is the change?
Remove this line and add a description

## Related issue?
closes: #issue_number

## Checklist:
Before you create this PR, confirm all the requirements listed below by checking the checkboxes `[x]`:

-   [x] I have followed the [Code of Conduct](https://github.com/HackClubRAIT/Wizard-Of-Docs/blob/ec224497bce316f7b4736a901f70688f251cca87/CODE_OF_CONDUCT.md).
-   [x] I have  checked there aren't other open [Pull Requests](https://github.com/siddhi-244/Embellish/pulls) for the same update/change.
-   [x] I have you tested the code before submission.
-   [x] I have commented my code, particularly in hard-to-understand areas.
-   [x] My changes generates no new warnings.
-   [x] I'm Hacktoberfest'21 contributor.

### CODE REVIEW

**Comment by rohith1125** [comment]
@girija0707 @siddhi-244 @das-jishu Could anyone of you please merge this PR

**Comment by siddhi-244** [comment]
> @girija0707 @siddhi-244 @das-jishu Could anyone of you please merge this PR

You haven't made any issue !

**Comment by rohith1125** [comment]
@siddhi-244 created the issue..

**Comment by siddhi-244** [comment]
> @siddhi-244 created the issue..

Wait for it to get assigned

**Comment by siddhi-244** [comment]
Refer to merged prs.  It should be a MD file

**Pull request closed without merging**
