### PR TITLE
Radix shell

### PR DESCRIPTION
**Pull request by vickyrules**
## What is the change?
Added shell and radix sorting algorithms.

## Related issue?
closes: #130 

## Checklist:
Before you create this PR, confirm all the requirements listed below by checking the checkboxes `[x]`:

-   [x] I have followed the [Code of Conduct](https://github.com/HackClubRAIT/Wizard-Of-Docs/blob/ec224497bce316f7b4736a901f70688f251cca87/CODE_OF_CONDUCT.md).
-   [x] I have  checked there aren't other open [Pull Requests](https://github.com/siddhi-244/Embellish/pulls) for the same update/change.
-   [x] I have you tested the code before submission.
-   [x] My changes generates no new warnings.
-   [x] I'm (HSOC) Hack-Club-Rait Summer of code '22 Contributor

### CODE REVIEW

**Comment by vickyrules** [comment]
@Chaitalishetty please review

**Review by Chaitalishetty — CHANGES_REQUESTED** [review]
@vickyrules Please add more description

**Comment by vickyrules** [comment]
@Chaitalishetty please check now.

**Review by Chaitalishetty — APPROVED** [review]
@vickyrules LGTM !

**Pull request merged**
