### PR TITLE
Inorder Tree Traversal

### PR DESCRIPTION
**Pull request by prasanna16-12**
## What is the change?
created folder
Algorithms -> Tree Traversal -> Inorder_Traversal.md
file contains
- description
- explanation
- psuedo code
- code (Recursive + Iterative)
- time and space complexity
## Related issue?
closes: #29 

## Checklist:
Before you create this PR, confirm all the requirements listed below by checking the checkboxes `[x]`:

-   [x] I have followed the [Code of Conduct](https://github.com/HackClubRAIT/Wizard-Of-Docs/blob/ec224497bce316f7b4736a901f70688f251cca87/CODE_OF_CONDUCT.md).
-   [x] I have  checked there aren't other open [Pull Requests](https://github.com/siddhi-244/Embellish/pulls) for the same update/change.
-   [x] I have you tested the code before submission.
-   [x] I have commented my code, particularly in hard-to-understand areas.
-   [x] My changes generates no new warnings.
-   [x] I'm Hacktoberfest'21 contributor.

### CODE REVIEW

**Review by siddhi-244 — APPROVED** [review]
Great work🎊🎊🎊

**Comment by siddhi-244** [comment]
Just delete the readme and make the folder name as tree @prasanna16-12

**Comment by siddhi-244** [comment]
> Just delete the readme and make the folder name as tree @prasanna16-12

Do this first

**Review by siddhi-244 — CHANGES_REQUESTED** [review]
Name the folder as Tree and remove the readme

**Review by siddhi-244 — APPROVED** [review]

**Comment by prasanna16-12** [comment]
review still pending

**Pull request merged**
