### PR TITLE
Added documentation on merge_sort

### PR DESCRIPTION
**Pull request by TD-17**
## What is the change?
Created a documentation on merge_sort

## Related issue?
closes: #30 

## Checklist:
Before you create this PR, confirm all the requirements listed below by checking the checkboxes `[x]`:

-   [x] I have followed the [Code of Conduct](https://github.com/HackClubRAIT/Wizard-Of-Docs/blob/ec224497bce316f7b4736a901f70688f251cca87/CODE_OF_CONDUCT.md).
-   [x] I have  checked there aren't other open [Pull Requests](https://github.com/siddhi-244/Embellish/pulls) for the same update/change.
-   [x] I have you tested the code before submission.
-   [x] I have commented my code, particularly in hard-to-understand areas.
-   [x] My changes generates no new warnings.
-   [x] I'm Hacktoberfest'21 contributor.

### CODE REVIEW

**Review by siddhi-244 — CHANGES_REQUESTED** [review]
It's plagiarized.  Please try to write it in ur own words

**Comment by TD-17** [comment]
@siddhi-244 I have completed the required changes. Could you please review it again?

**Comment by TD-17** [comment]
@siddhi-244 Could you please review the changes?

**Comment by siddhi-244** [comment]
Yes wait

**Review by siddhi-244 — APPROVED** [review]

**Comment by TD-17** [comment]
@girija0707 Please review my PR.

**Pull request merged**
