### PR TITLE
Add Array Problems

### PR DESCRIPTION
**Pull request by PriyanshuGarg26**
## What is the change?
Add TwoSumII.md , 3Sum.md , Topkfrequentelements.md in Array Folders 

## Related issue?
closes: #issue_number 129

## Checklist:

-   [x] I have followed the [Code of Conduct](https://github.com/HackClubRAIT/Wizard-Of-Docs/blob/ec224497bce316f7b4736a901f70688f251cca87/CODE_OF_CONDUCT.md).
-   [x] I have  checked there aren't other open [Pull Requests](https://github.com/siddhi-244/Embellish/pulls) for the same update/change.
-   [x] I have you tested the code before submission.
-   [x] I have commented my code, particularly in hard-to-understand areas.
-   [x] My changes generates no new warnings.
-   [x] I'm (HSOC) Hack-Club-Rait Summer of code '22 Contributor

### CODE REVIEW

**Review by PriyanshuGarg26 — COMMENTED** [review]
ok

**Comment by Chaitalishetty** [comment]
@PriyanshuGarg26 Please add some explanation for the code.

**Comment by PriyanshuGarg26** [comment]
ok Sure

**Review by Chaitalishetty — APPROVED** [review]
LGTM !

**Pull request merged**
